### ISSUE TITLE
Cannot find module 'optipng-bin'

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [firetix/gulp-image-optimization#4]
I get the following error when using with gulp `Cannot find module 'optipng-bin'`

**Comment by firetix** [comment]
Hey @theboyWhoCriedWoolf  are you still experiencing issues with this? I think I didn't add 'optipng-bin' as a dependency. Going to do that

**Comment by Nightbr** [comment]
Hi, same problem here. Can you add 'optipng-bin' as a dependency please ?

**Comment by chadidi** [comment]
same problem using `"gulp-image-optimization": "^0.1.3"`

**Comment by NickStees** [comment]
Same problem, when running `npm install ` I am getting errors such as below. I am using Node v6.11.3 on windows. From Googling it seems like it has something to do with using the Newer Node v6 version and maybe you have to use Node v4.x ???

```
> optipng-bin@0.3.11 postinstall C:\project\node_modules\optipng-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/win/optipng.exe',
  name: 'optipng.exe',
  os: 'win32' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at C:\project\node_modules\download\index.js:35:43
    at each (C:\project\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\project\node_modules\download\index.js:33:5)
    at C:\project\node_modules\bin-wrapper\index.js:108:20
    at C:\project\node_modules\bin-wrapper\index.js:141:24
    at C:\project\node_modules\bin-check\index.js:30:20
    at C:\project\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by firetix** [comment]
This have been fixed closing
