### ISSUE TITLE
Bad argument error when running

### ISSUE THREAD

**Issue by VRedondo** [firetix/gulp-image-optimization#6]
Hi

Im running the gulp task with exactly the same code that appears in the README.md and when running the task it throws the next error in the console.

Internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)

is there something Im missing,
Thanks for your help

**Comment by nielsenrc** [comment]
Same error here. Any help? This is using the example on the NPM page.

**Comment by tomhatzer** [comment]
Got the same error when running the script...

MBP:~ tom$ npm -v
3.10.3
MBP:~ tom$ node -v
v6.7.0
MBP:~ tom$ ./node_modules/.bin/phantomjs -v
2.1.1
