### ISSUE TITLE
not compatible with node v6

### ISSUE THREAD

**Issue by wasap** [firetix/gulp-image-optimization#7]
> gifsicle@0.1.7 postinstall /Users/vasap/proj/node_modules/gifsicle
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/gifsicle-bin/v0.1.7/vendor/osx/gifsicle',
  name: 'gifsicle',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/vasap/proj/node_modules/download/index.js:35:43
    at each (/Users/vasap/proj/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/vasap/proj/node_modules/download/index.js:33:5)
    at /Users/vasap/proj/node_modules/bin-wrapper/index.js:108:20
    at /Users/vasap/proj/node_modules/bin-wrapper/index.js:141:24
    at /Users/vasap/proj/node_modules/bin-check/index.js:30:20
    at /Users/vasap/proj/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)

> jpegtran-bin@0.2.8 postinstall /Users/vasap/proj/node_modules/jpegtran-bin
> node index.js

> optipng-bin@0.3.11 postinstall /Users/vasap/proj/node_modules/optipng-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/osx/optipng',
  name: 'optipng',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/vasap/proj/node_modules/download/index.js:35:43
    at each (/Users/vasap/proj/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/vasap/proj/node_modules/download/index.js:33:5)
    at /Users/vasap/proj/node_modules/bin-wrapper/index.js:108:20
    at /Users/vasap/proj/node_modules/bin-wrapper/index.js:141:24
    at /Users/vasap/proj/node_modules/bin-check/index.js:30:20
    at /Users/vasap/proj/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
proj@1.0.0 /Users/vasap/proj

**Comment by tomhatzer** [comment]
When fixing this, #6 will happen.

**Comment by firetix** [comment]
Thanks @tomhatzer I'll take a look

**Comment by maketimetodesign** [comment]
Getting the same issue. Not in any way shape or form hassling (!) but, I was wondering if you had any news on this @firetix? Only so as I can explore alternatives if needs be.

Seems to me that gifsicle@0.1.7 / optipng-bin@0.3.11 etc are out of date? Or I am way off the mark? Thanks in advance!

**Comment by khaledosman** [comment]
same

**Comment by matfricker** [comment]
I am having the same issue on node v6.10.0:

- gifsicle
- jpegtran-bin
- optipng-bin

Error: throw new TypeError('Path must be a string. Received ' + inspect(path));

**Comment by khaledosman** [comment]
Any updates on this?

**Comment by jdunk** [comment]
Is this possibly just a matter of switching from `image-min` to `imagemin` ?

See this comment: https://github.com/imagemin/imagemin/issues/228#issuecomment-304835814

**Comment by firetix** [comment]
I did switch image-min to imagemin. @jdunk you can see on the https://github.com/imagemin/imagemin repository that they don't support v6 of node. if you guys have another solution let me know
